### ISSUE TITLE
Enhancement: Duplicate into specific vertex groups

### ISSUE THREAD

**Issue by Riverface** [MichaelGlenMontague/shape_keys_plus#4]
I would love to have a function that more-or-less automatically copies shape keys and blends them with specific vertex groups.
For example, if I have a character and I want to adopt the FACS expression system (something a lot of people should do!) it's kind of time-consuming to go through and split them up for Face.L and Face.R.

**Comment by MontagueMGM** [comment]
I'll add more functionality to the Copy Shape Key operator that lets you choose whether to copy or replace certain properties. This would include the ability to change which vertex group the newly copied shape keys will use.

I'm not sure if it would be feasible to add in another 1.3 patch, but it'll definitely be in 2.0.

**Comment by MichaelGlenMontague** [comment]
I just uploaded a v2.0 RC to the `develop` branch, and this upgraded Copy Shape Key operator is now available under the respective context menu. If you want to test it before it's officially released, clone the branch and rename the extracted folder to "shape_keys_plus".
