### ISSUE TITLE
Enhancement: Blend selected verts from selected keys to basis

### ISSUE THREAD

**Issue by Riverface** [MichaelGlenMontague/shape_keys_plus#5]
Something I've noticed while working with shape keys is that when you edit unrelated verts in the basis, what you've edited becomes a crumpled mess when you go to use shape keys because the keys want to compensate for the difference they have from the basis.
So, having a batch operation to fix all of that quickly would be very convenient!

**Comment by MontagueMGM** [comment]
I think I've attempted an add-on solution before, but there are already built-in ways to avoid this from happening. Have you tried this method? https://blender.stackexchange.com/a/58592
